version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
        steps:
          - run: npm install
          - run: npm run build
workflows:

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
