version: 2
jobs:
  step-one:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run lint && npm test

workflows:
  version: 2
  main:
    jobs:
      - step-one
